# Generated by Django 4.2.20 on 2025-04-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='original_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='files.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='reference_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
