# Generated by Django 4.2.20 on 2025-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_is_reference_file_original_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', False)), fields=('hash',), name='unique_hash_for_non_reference'),
        ),
    ]
